name: Deploy Release to Vercel

on:
  push:
    branches:
      - "release/**" # any branch starting with release/

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Deploy to Vercel
        run: |
          npm install -g vercel
          vercel deploy --prod --token ${{ secrets.VERCEL_TOKEN }} \
            --org-id ${{ secrets.VERCEL_ORG_ID }} \
            --project-id ${{ secrets.VERCEL_PROJECT_ID }} \
            --confirm --yes
